
[functions.send-indexing-notification]
enabled = true
verify_jwt = true
import_map = "./functions/send-indexing-notification/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-indexing-notification/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-indexing-notification/*.html" ]

[functions.process-mail-notification]
enabled = true
verify_jwt = true
import_map = "./functions/process-mail-notification/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-mail-notification/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-mail-notification/*.html" ]

[functions.perform-trademark-similarity-search]
enabled = true
verify_jwt = true
import_map = "./functions/perform-trademark-similarity-search/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/perform-trademark-similarity-search/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/perform-trademark-similarity-search/*.html" ]

[functions.process-bulletin]
enabled = true
verify_jwt = true
import_map = "./functions/process-bulletin/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-bulletin/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-bulletin/*.html" ]

[functions.generate-similarity-report]
enabled = true
verify_jwt = true
import_map = "./functions/generate-similarity-report/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-similarity-report/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-similarity-report/*.html" ]

[functions.create-objection-task]
enabled = true
verify_jwt = true
import_map = "./functions/create-objection-task/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-objection-task/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-objection-task/*.html" ]
